### PR TITLE
Making HBO GO videos work with the extension enabled

### PR DESCRIPTION
**Pull request by mariusi7**
I had this problem with the Chrome original extension and found a fix recently. See igrigorik#199;
I need to see if the speed is preserved in Firefox. In Chrome I can change the speed but it's reset to 1.0 after a few seconds.
Second attempt for a PR with the needed commits.

### CODE REVIEW

**Comment by mariusi7** [comment]
Note that during conflict solving I kept only my changes in the file, reverted the other 2 commits.

**Comment by mariusi7** [comment]
In the end I did manage to install the changed add-on temporarly and video plays now and speed changing works fine on HBO GO, but it's reset to 1.0 just like in Chrome. Very sad..
@codebicycle maybe you can look at https://www.hbogo.ro/group/free and have some ideas? The original developer (Igor) doesn't have access to any HBO site

**Comment by codebicycle** [comment]
I was able to replicate the speed reset bug in Firefox.
From what I saw it happens when a new video is played, on seek and on playback especially when the internet connection speed is slow.

This extension will stay as close as possible to the Chrome one.
I will not accept this pull request, but I will merge changes from the upstream Chrome extension when a new version is released.

Thanks for your contribution!

**Comment by mariusi7** [comment]
Thank you. That's fine by me.

**Comment by mariusi7** [comment]
Hi. Can you create a new version out of 0.4.9? 
I see someone else wanting to use HBO GO websites in FF https://github.com/igrigorik/videospeed/issues/199

**Comment by mariusi7** [comment]
We need version 0.4.9. Or some way to use hbogo.* when extension is enabled

**Comment by codebicycle** [comment]
I've sent version 0.4.9 to Mozilla for review. It will be available shortly.

**Pull request closed without merging**
