### PR TITLE
fix youtube fullscreen resets playback speed

### LINKED ISSUE #50: Playback speed resets to 1.00 when entering/exiting fullscreen mode on YouTube
I'm using Firefox.

### PR DESCRIPTION
**Pull request by sloganking**
fixes codebicycle#50

I mostly just copied the necessary changes made to fix the same issue for the Chrome Repo here:

https://github.com/igrigorik/videospeed/pull/447/files

I did not independently verify that there are no issues with this repo's existing code but everything seems to work fine for me. Please look over the code and test it out yourself.

### CODE REVIEW

**Comment by iSytrus** [comment]
Thank you very much. Is there any way i can install this fix manually?

**Comment by sloganking** [comment]
@iSytrus as talked about in another pull request

https://github.com/codebicycle/videospeed/pull/45#issuecomment-554239548

Download the files from this pull request and put them in a .zip file. Currently the files can be found in this commit

https://github.com/SleepingFox88/videospeed/tree/94cbc7ea831bf8bbb041bb9b0d1e7a45cd1a705d

then in firefox, goto ``about:debugging#addons`` and load the zip file.

Seeing as that is how to add a temporary addon the add-on will be unloaded every time when Firefox is closed. If you find a way to publish the addon for private or public use, the addon will no longer be removed upon restarting.

I think steps to do that can be found in [this video at 3:29](https://youtu.be/P0ugObgYohY?t=209)

**Comment by alekksander** [comment]
it does fix the issue, but at this moment i cannot get videospeed controller to actually work. it displays current speed correctly, but controller button's do anything. perhaps @SleepingFox88 You are skilled enough to update and maintain this piece of software for firefox?

**Comment by sloganking** [comment]
@alekksander when referencing ``controller button's do nothing``are you talking about an issue introduced by this pull request or with the current master build? If it's not already in issues, feel free to create an issue for your problem.

I am not overly familiar with browser extension development, but I will look at this repository and see what more I can contribute.

**Comment by sloganking** [comment]
Per [this discussion](https://github.com/codebicycle/videospeed/issues/50#issuecomment-618048133), this issue has been resolved by someone else. Closing this PR for now.

**Pull request closed without merging**
